---
title: "Baseline Travel Survey Summary ITHIM-R"
author: ""
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 5
    toc_float: true
    number_sections: true
---

Note: in order to create the markdown properly from this file, Rstudio options need to be changed. Tools > Global Options > R Markdown > Evaluate chunks in directory > Current. By default this option is set to *Document*, but here you need to change it to *Current* so everything works as expected.

```{r, include = FALSE}
source("code/producing_trips_rd/used_functions.R")
knitr::opts_chunk$set(comment=NA, prompt=FALSE, cache=FALSE, echo=F, results='asis')
```

```{r loadLibraries, echo = F, message = F}

st_options(bootstrap.css     = FALSE,       # Already part of the theme so no need for it
           plain.ascii       = FALSE,       # One of the essential settings
           style             = "rmarkdown", # Idem.
           dfSummary.silent  = TRUE,        # Suppresses messages about temporary files
           footnote          = NA,          # Keeping the results minimalistic
           subtitle.emphasis = FALSE)       # For the vignette theme, this gives
                                            # much better results. Your mileage may vary

```

```{r,  comment=NA, message=FALSE, warning=FALSE, prompt=FALSE, cache=FALSE, echo=F}
# (readxl::read_excel("C:/Users/danie/Documents/Daniel_Gil/Consultorias/2020/WorldBank/ITHIM-R/code/producing_trips_rd/Travel_survey_details.xlsx")
#   ) %>% kbl() %>% kable_classic()

# (If short walk is not explicitly recorded, we have to find a way to remove; if they are missing, what should we do?)

# Sao Paulo:
# 1) Walking trips: Page 60, Pesquisa de Mobilidade da RMSP –2012 –Manual da Pesquisa Domiciliar
# Belo horizonte:
# 1) Study area: page 35, codebook and protocol.pdf
# Cape town:
# 1) Main mode Hierarchy: page 45, Final Draft HH Survey Report.pdf
```

```{r,  comment=NA, message=FALSE, warning=FALSE, prompt=FALSE, cache=FALSE, echo=F}
trip <- read_csv("data/local/buenos_aires/buenos_aires_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Buenos_Aires <- value

trip <- read_csv("data/local/sao_paulo/sao_paulo_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Sao_Paulo <- value

trip <- read_csv("data/local/belo_horizonte/belo_horizonte_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Belo_Horizonte <- value

trip <- read_csv("data/local/mexico_city/mexico_city_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Mexico <- value

trip <- read_csv("data/local/bogota/bogota_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Bogota <- value

trip <- read_csv("data/local/santiago/santiago_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Santiago <- value

trip <- read_csv("data/local/vizag/vizag_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Visakhapatnam <- value

trip <- read_csv("data/local/delhi/delhi_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Delhi <- value

trip <- read_csv("data/local/bangalore/bangalore_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Bangalore <- value

trip <- read_csv("data/local/accra/accra_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Accra <- value

trip <- read_csv("data/local/cape_town/cape_town_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Cape_Town <- value

###
trip <- read_csv("data/local/antofagasta/antofagasta_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Antofagasta <- value

trip <- read_csv("data/local/arica/arica_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Arica <- value

trip <- read_csv("data/local/cali/cali_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Cali <- value

trip <- read_csv("data/local/copiapo/copiapo_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Copiapo <- value

trip <- read_csv("data/local/coquimbo_laserena/coquimbo_laserena_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Coquimbo <- value

trip <- read_csv("data/local/gran_valparaiso/gran_valparaiso_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Gran_Valparaiso <- value

trip <- read_csv("data/local/iquique_altohospicio/iquique_altohospicio_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Iquique <- value

trip <- read_csv("data/local/medellin/medellin_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Medellin <- value

trip <- read_csv("data/local/montevideo/montevideo_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Montevideo <- value

trip <- read_csv("data/local/osorno/osorno_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Osorno <- value

trip <- read_csv("data/local/puerto_montt/puerto_montt_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Puerto_montt <- value

trip <- read_csv("data/local/san_antonio/san_antonio_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$San_antonio <- value

trip <- read_csv("data/local/temuco_padrelascasas/temuco_padrelascasas_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Temuco <- value

trip <- read_csv("data/local/valdivia/valdivia_trips.csv",
                 guess_max = 100000)
quality_check(trip)
trip_summary$Valdivia <- value



```

```{r,  comment=NA, message=FALSE, warning=FALSE, prompt=FALSE, cache=FALSE, echo=F}
trip <- read_csv("data/local/buenos_aires/buenos_aires_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Buenos_Aires <- value

trip <- read_csv("data/local/sao_paulo/sao_paulo_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Sao_Paulo <- value

trip <- read_csv("data/local/belo_horizonte/belo_horizonte_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Belo_Horizonte <- value

trip <- read_csv("data/local/mexico_city/mexico_city_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Mexico <- value

trip <- read_csv("data/local/bogota/bogota_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Bogota <- value

trip <- read_csv("data/local/santiago/santiago_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Santiago <- value

trip <- read_csv("data/local/vizag/vizag_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Visakhapatnam <- value

trip <- read_csv("data/local/delhi/delhi_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Delhi <- value

trip <- read_csv("data/local/bangalore/bangalore_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Bangalore <- value

trip <- read_csv("data/local/accra/accra_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Accra <- value

trip <- read_csv("data/local/cape_town/cape_town_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Cape_Town <- value

###
trip <- read_csv("data/local/antofagasta/antofagasta_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Antofagasta <- value

trip <- read_csv("data/local/arica/arica_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Arica <- value

trip <- read_csv("data/local/cali/cali_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Cali <- value

trip <- read_csv("data/local/copiapo/copiapo_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Copiapo <- value

trip <- read_csv("data/local/coquimbo_laserena/coquimbo_laserena_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Coquimbo <- value

trip <- read_csv("data/local/gran_valparaiso/gran_valparaiso_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Gran_Valparaiso <- value

trip <- read_csv("data/local/iquique_altohospicio/iquique_altohospicio_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Iquique <- value

trip <- read_csv("data/local/medellin/medellin_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Medellin <- value

trip <- read_csv("data/local/montevideo/montevideo_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Montevideo <- value

trip <- read_csv("data/local/osorno/osorno_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Osorno <- value

trip <- read_csv("data/local/puerto_montt/puerto_montt_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Puerto_montt <- value

trip <- read_csv("data/local/san_antonio/san_antonio_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$San_antonio <- value

trip <- read_csv("data/local/temuco_padrelascasas/temuco_padrelascasas_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Temuco <- value

trip <- read_csv("data/local/valdivia/valdivia_trips.csv",
                 guess_max = 100000)
quality_check(trip, 15, 69)
trip_summary2$Valdivia <- value
```

## summary table (all rows)
```{r, include = TRUE,  echo= FALSE, results='asis'}
kable(trip_summary) %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), font_size = 14, fixed_thead = T)
  
```

## summary table (only people between 15 and 69)
```{r, include = TRUE,  echo= FALSE, results='asis'}
kable(trip_summary2) %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), font_size = 14, fixed_thead = T)
  
```

