---
title: "AP/PA Tables ITHIM Global"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    toc: true
    toc_depth: 5
    toc_float: true
  word_document: default
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(comment=NA, prompt=FALSE, cache=FALSE, echo=F, results='asis')

```


# Introduction
These are the summary tables of the following items

1) Individual-level PM2.5 concentrations for baseline and scenarios
2) Overall CO2 emissions for baseline and scenarios
3) Individual-level physical activity for baseline and scenarios



```{r, echo=FALSE}
#setwd('C:/Users/rg574/Dropbox/spatiotemporal analysis fatalities inida/Rajasthan tourism road deaths') #to create pretty tables
```

```{r, message=FALSE, warning=FALSE}
#library(INLA)     #loading the INLA package
library(ggplot2)  #loading ggplot package for plotting graphs
library(knitr)     
library(tidyr)
library(dplyr)
library(plotly)

```


# Boxplots of Individual-level PM2.5 Concentrations

```{r, message=FALSE, warning=FALSE, echo=FALSE, cache=TRUE}
io <- readRDS("results/multi_city/io.rds")

# Assumes that multi_city_script.R has been run till 
# Get names of cities from the io object
cities <- names(io)[!names(io) %in% 'scen_prop']


all_inputs <- read.csv('all_city_parameter_inputs.csv',stringsAsFactors = F)

#all_inputs$cape_town <- all_inputs$accra
#all_inputs$vizag <- all_inputs$sao_paulo

parameter_names <- all_inputs$parameter
parameter_starts <- which(parameter_names != '')
parameter_stops <- c(parameter_starts[-1] - 1, nrow(all_inputs))
parameter_names <- parameter_names[parameter_names != '']
parameter_list <- list()
compute_mode <- 'constant'
for (i in 1:length(parameter_names)) {
  parameter_list[[parameter_names[i]]] <- list()
  parameter_index <- which(all_inputs$parameter == parameter_names[i])
  if (all_inputs[parameter_index,2] == '') {
    parameter_list[[parameter_names[i]]] <- lapply(cities,function(x) {
      city_index <- which(colnames(all_inputs) == x)
      val <- all_inputs[parameter_index,city_index]
      ifelse(val %in% c('T','F'),val,as.numeric(val))
    })
    names(parameter_list[[parameter_names[i]]]) <- cities
  }else if (all_inputs[parameter_index,2] == 'constant') {
    indices <- 0
    if (compute_mode == 'sample') indices <- 1:2
    parameter_list[[parameter_names[i]]] <- lapply(cities,function(x) {
      city_index <- which(colnames(all_inputs) == x)
      val <- all_inputs[parameter_index + indices,city_index]
      ifelse(val == '',0,as.numeric(val))
    })
    names(parameter_list[[parameter_names[i]]]) <- cities
  }else{
    parameter_list[[parameter_names[i]]] <- lapply(cities,function(x) {
      city_index <- which(colnames(all_inputs) == x)
      if (any(all_inputs[parameter_starts[i]:parameter_stops[i],
                         city_index] != '')) {
        sublist_indices <- which(all_inputs[parameter_starts[i]:parameter_stops[i],city_index] != '')
        thing <- as.list(as.numeric(c(all_inputs[parameter_starts[i]:parameter_stops[i],city_index])[sublist_indices]))
        names(thing) <- c(all_inputs[parameter_starts[i]:parameter_stops[i],2])[sublist_indices]
        thing
      }
    }
    )
    names(parameter_list[[parameter_names[i]]]) <- cities
  }
}

for (i in 1:length(parameter_list))  assign(names(parameter_list)[i],parameter_list[[i]])
```

```{r}
# high<- c(70, 25, 150,60)
# low<- c(40,15,100,40)
for (x in 1:length(cities)) {
  # print(cities[x])
  names(io[[cities[x]]]$outcomes$pm_conc_pp)[6:11] <- c("Baseline","Walking",
                                                        "Bicycling", "Driving",
                                                        "Motorcycling", 
                                                        "Public Transport")
  data_long <- gather(io[[cities[x]]]$outcomes$pm_conc_pp, scenario, pm_conc,
                      Baseline:`Public Transport`, factor_key = TRUE)
  y <- ggplot(data_long, aes(x = scenario, y = pm_conc, fill = scenario)) +
    geom_boxplot(outlier.shape = 8) + ggtitle(cities[x]) +
    labs(y = "Daily PM2.5 Concentration", x = "Scenarios") #+ 
    #ylim(min(data_long$pm_conc), max(data_long$pm_conc) + 10)
    #+ylim(low[x],high[x])
  yy <- ggplot() +
    geom_density(data_long, aes(x = scenario, y = pm_conc, fill = scenario)) +
    ggtitle(cities[x]) +
    labs(y = "Daily PM2.5 Concentration", x = "Scenarios")
  #print(y)
  #print(yy)
  print(ggplotly(y))
  print(ggplotly(yy))
}
```

