---
title: "Summary Outcome Tables"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 5
    toc_float: true
---

```{r setup, include=FALSE}
library(knitr)
library(pracma)
library(summarytools)
library(dplyr)
library(purrr)
library(flextable)
library(ggplot2)
library(tidyr)
knitr::opts_chunk$set(comment=NA, prompt=FALSE, cache=FALSE, echo=F, message = F, warning = F, results='asis')

```


```{r loadLibraries, echo = F, message = F}

st_options(bootstrap.css     = FALSE,       # Already part of the theme so no need for it
           plain.ascii       = FALSE,       # One of the essential settings
           style             = "rmarkdown", # Idem.
           dfSummary.silent  = TRUE,        # Suppresses messages about temporary files
           footnote          = NA,          # Keeping the results minimalistic
           subtitle.emphasis = FALSE)       # For the vignette theme, this gives
# much better results. Your mileage may vary

```

```{r load_objects = "asis"}
io <- readRDS("results/multi_city/io.rds")
# Assumes that multi_city_script.R has been run till 
cities <- c('accra','sao_paulo','delhi','bangalore', 'santiago', 'belo_horizonte', 'buenos_aires', 'bogota',
            'mexico_city', 'vizag')

cities <- names(io)[!names(io) %in% 'scen_prop']

round_to <- 1

# Set plot_mmets to F
plot_mmets <- F

sum_and_round_and_print <- function(data,text=''){
  data <- lapply(data, function(x)round(x,round_to))
  data <- lapply(data,function(x)rbind(x,Total=colSums(x)))
  for(city in cities) {
    print(kable(data[[city]], caption = paste(text, city)))
    cat("\n")
  }
}
round_and_print <- function(data,text=''){
  data <- lapply(data, function(x)round(x,round_to))
  for(city in cities) {
    print(kable(data[[city]], caption = paste(text, city)))
    cat("\n")
  }
}

```


```{r preprocessing}


collapse_ages <- function(data,ages=c('15-49','50-69'),age_lab='age_cat'){
  target_min_age <- as.numeric(sapply(ages,function(x)strsplit(x,'-')[[1]][1]))
  target_max_age <- as.numeric(sapply(ages,function(x)strsplit(x,'-')[[1]][2]))
  min_ages <- as.numeric(sapply(data[[age_lab]],function(x)strsplit(x,'-')[[1]][1]))
  max_ages <- as.numeric(sapply(data[[age_lab]],function(x)strsplit(x,'-')[[1]][2]))
  genders <- unique(data$sex)
  if(ncol(data)>3) {
    reformatted <- do.call(rbind,lapply(1:length(ages),
                                        function(x) t(sapply(genders,
                                                             function(y) 
                                                               if(ncol(data)>3) colSums(data[min_ages<=target_max_age[x]&max_ages>=target_min_age[x]&data$sex==y,-c(1,2),drop=F])
                                                             else sum(data[min_ages<=target_max_age[x]&max_ages>=target_min_age[x]&data$sex==y,-c(1,2),drop=F])
                                        ))
    ))
    data.frame(age_cat=rep(ages,each=2),sex=rep(genders,2),reformatted,stringsAsFactors=F)
  }else{
    reformatted <- do.call(c,lapply(1:length(ages),
                                    function(x) sapply(genders,
                                                       function(y) 
                                                         sum(data[min_ages<=target_max_age[x]&max_ages>=target_min_age[x]&data$sex==y,-c(1,2),drop=F])
                                    )
    ))
    data.frame(age=rep(ages,each=2),sex=rep(genders,2),population=as.numeric(reformatted),stringsAsFactors=F)
  }
}

scen_prop <- io$scen_prop
io <- io[-2]
for(i in 1:length(io)) {
  io[[i]]$demographic$age[io[[i]]$demographic$age=='5-9'] <- '05-9'
  io[[i]]$outcomes$hb$deaths$age_cat[io[[i]]$outcomes$hb$deaths$age_cat=='5-9'] <- '05-9'
  io[[i]]$outcomes$hb$ylls$age_cat[io[[i]]$outcomes$hb$ylls$age_cat=='5-9'] <- '05-9'
  io[[i]]$outcomes$pathway_hb$deaths$age_cat[io[[i]]$outcomes$pathway_hb$deaths$age_cat=='5-9'] <- '05-9'
  io[[i]]$outcomes$pathway_hb$ylls$age_cat[io[[i]]$outcomes$pathway_hb$ylls$age_cat=='5-9'] <- '05-9'
  io[[i]]$outcomes$hb$deaths <- io[[i]]$outcomes$hb$deaths[,!sapply(names(io[[i]]$outcomes$hb$deaths),function(x)grepl('ac|neo',as.character(x)))]
  io[[i]]$outcomes$hb$ylls <- io[[i]]$outcomes$hb$ylls[,!sapply(names(io[[i]]$outcomes$hb$ylls),function(x)grepl('ac|neo',as.character(x)))]
  io[[i]]$outcomes$pathway_hb$deaths <- io[[i]]$outcomes$pathway_hb$deaths[,!sapply(names(io[[i]]$outcomes$pathway_hb$deaths),function(x)grepl('ac|neo',as.character(x)))]
  io[[i]]$outcomes$pathway_hb$ylls <- io[[i]]$outcomes$pathway_hb$ylls[,!sapply(names(io[[i]]$outcomes$pathway_hb$ylls),function(x)grepl('ac|neo',as.character(x)))]
}
for(city in cities)
  for(type in c('hb','pathway_hb'))
    for(out in c('deaths','ylls'))
      io[[city]]$outcomes[[type]][[out]] <- collapse_ages(io[[city]]$outcomes[[type]][[out]])
for(city in cities) io[[city]]$demographic <- collapse_ages(io[[city]]$demographic,age_lab='age')
pop_by_age <- lapply(io,function(x)sapply(unique(x$demographic$age),function(y)sum(subset(x$demographic,age==y)$population)))
pop_by_gender <- lapply(io,function(x)sapply(unique(x$demographic$sex),function(y)sum(subset(x$demographic,sex==y)$population)))
injury_col <- which(colnames(io[[1]]$outcomes$hb$deaths)=='scen1_deaths_inj')
ap_cols <- which(sapply(colnames(io[[1]]$outcomes$pathway_hb$deaths),function(x)grepl('ap',as.character(x))))
pa_cols <- which(sapply(colnames(io[[1]]$outcomes$pathway_hb$deaths),function(x)grepl('pa',as.character(x))))
scen_names <- rownames(scen_prop)
# scen_names <- c('Walking', 'Bicycling', 'Driving', 'Public Transport', 'Motorcycling')


```

# Who Hit Whom matrix (normalized to annual figures)

Who hit whom matrix for all scenarios for each case study

## Who hit whom matrix of each case study (by baseline + scenarios) {#whw}

```{r whw}

scen_names_w_baseline <- c('bl', 'w_sc', 'bi_sc', 'car_sc', 'mc_sc', 'bus_sc')
scen_lt <- data.frame("scen_name" = names(io$accra$outcomes$whw), "val" = scen_names_w_baseline, stringsAsFactors = FALSE)

all_whw <- list()

for(city in cities){
  {
    cat('\n')
    
    cat('###', city, '\n')

    for (cs in names(io$accra$outcomes$whw)){
      
      if (is.null(io[[city]]$outcomes$whw[[cs]]$whw)){
        if (!is.null(io[[city]]$outcomes$whw[[cs]]$nov)){
          td2 <- t(io[[city]]$outcomes$whw[[cs]]$nov) %>% as.data.frame()
          td2$mode <- 'NOV'
          
          td2 <- td2 %>% dplyr::select(mode, names(.))
          
          td3 <- td2
        }
        
      }else{
        td1 <- (io[[city]]$outcomes$whw[[cs]]$whw) %>% as.data.frame() %>% tibble::rownames_to_column("mode")
        td3 <- td1
        if (!is.null(io[[city]]$outcomes$whw[[cs]]$nov)){
          td2 <- t(io[[city]]$outcomes$whw[[cs]]$nov) %>% as.data.frame()
          td2$mode <- 'NOV'
          
          td3 <- plyr::rbind.fill(td1, td2)
        }
      }
      td3 <- td3 %>% mutate(rowSum = rowSums(.[2:ncol(td3)], na.rm = T))
      td3 <- td3 %>% janitor::adorn_totals("row")
      td3[, 2:ncol(td3)] <- round(td3[, 2:ncol(td3)], 2)
      
      var <- scen_lt %>% filter(scen_name == cs) %>% dplyr::select(val) %>% as.character()
      
      # scen_names <- c('Walking', 'Bicycling', 'Driving', 'Public Transport', 'Motorcycling')
      
      
      if (var == 'bl'){
        qualified_scen_name <- 'Baseline'
        scen <- ''
      }else if(var == "w_sc"){
        qualified_scen_name <- 'Walking'
      }else if(var == "bi_sc"){
        qualified_scen_name <- 'Bicycling'
      }else if(var == "car_sc"){
        qualified_scen_name <- 'Driving'
      }else if(var == "mc_sc"){
        qualified_scen_name <- 'Motorcyling'
      }else if(var == "bus_sc"){
        qualified_scen_name <- 'Public Transport'
      }
      
      cat('\n')
      
      cat('####', qualified_scen_name, ' WHW', '\n')
      
      cat('\n')


      
      temp <- td3 %>% mutate_if(is.numeric, .funs = funs(case_when( . < 1 ~ round(., 2) ,  . >= 1 ~  as.numeric(round(.))))) %>%  mutate_if(is.numeric, ~as.character(.))
      
      ft <- flextable(temp)
      ft <- autofit(ft)
      cat(knit_print(ft))
      
      #print(kable(format(td3, scientific = F), caption = paste('Who Hit Whom (WHW) ', qualified_scen_name, ' scenario matrix for ', city)))
      cat("\n")
      
      td <- td3
      names(td)[2:ncol(td)] <- paste(names(td)[2:ncol(td)], city, sep = "_")
      
      all_whw[[var]][[city]] <- td
    }
    
  }
}

```


```{r whw_for_all_cs, results = 'asis', fig.width=7, fig.height=4, echo=FALSE}

st <- list()

file_list <- list()

td <- NULL

whw_list <- list()

for (cs in names(all_whw)){
  # cs <- names(all_whw)[1]
  
  td <- all_whw[[cs]] %>% purrr::reduce(full_join, by = "mode") %>% as.data.frame() %>% dplyr::select(mode, sort(names(.)))
  
  td[is.na(td)] <- 0
  
  # unk <- td %>% filter(mode %in% c('unknown', 'unk')) %>% summarise_if(is.numeric, sum) %>% mutate(mode = 'unknown')
  # 
  # unsp <- td %>% filter(mode %in% c('unspecified', 'listed_na', '?')) %>% summarise_if(is.numeric, sum) %>% mutate(mode = 'unspecified')
  # 
  # other <- unsp <- td %>% filter(mode %in% c('other', 'non.motor.vehicle', 'tract', 'railway.train.railway.vehicle')) %>% summarise_if(is.numeric, sum) %>% mutate(mode = 'other')
  # 
  # pu <- td %>% filter(mode %in% c('picku', 'pickup/light goods')) %>% summarise_if(is.numeric, sum) %>% mutate(mode = 'pickup')
  # 
  # bus <- td %>% filter(mode %in% c('bus', 'bus_driver')) %>% summarise_if(is.numeric, sum) %>% mutate(mode = 'bus')
  # 
  # td <- td %>% filter(!mode %in% c('bus', 'bus_driver', 'unknown', 'unk', 'unspecified', 'listed_na', '?', 
  #                                  'other', 'non.motor.vehicle', 'tract', 'railway.train.railway.vehicle',
  #                                  'picku', 'pickup/light goods'))
  # 
  # td <- plyr::rbind.fill(td, bus, unk, unsp, other, pu)
  # 
  td <- (td[!duplicated(td), ])
  
  td <- rbind(td %>% dplyr::filter(!mode %in% c("Total", "NOV")) %>% arrange(mode), td %>% filter(mode == 'NOV'), td %>% filter(mode == 'Total'))
  
  td[is.na(td)] <- 0
  
  td <- td %>% mutate_if(is.numeric, round, 2)
  
  backup_td <- td
  
  # readr::write_csv(td, paste0('results/multi_city/whw_matrices/whw_', cs, '.csv'))
  
  colnames(td) = gsub("auto_rickshaw", "ar", colnames(td))
  
  whw_lng <- reshape2::melt(td)
  
  col_split <- stringr::str_split(whw_lng$variable, "_", simplify = TRUE, n = 2)
  
  whw_lng <- cbind(whw_lng, col_split)
  names(whw_lng)[4] <- 'strike_mode'
  names(whw_lng)[5] <- 'city'
  whw_lng <- whw_lng %>% dplyr::select(-variable)
  whw_lng <- whw_lng %>% dplyr::filter(strike_mode != "rowSum")
  whw_lng <- whw_lng %>% rename(str_mode = mode, cas_mode = strike_mode)
  
  whw_lng$str_mode <- factor(whw_lng$str_mode, levels = unique(whw_lng$str_mode))
  
  # scen_names <- c('Walking', 'Bicycling', 'Driving', 'Public Transport', 'Motorcycling')
  
  qualified_scen_name <- 'Public Transport'
  scen <- 'Scenario'
  
  if (cs == 'bl'){
    qualified_scen_name <- 'Baseline'
    scen <- ''
  }else if(cs == "w_sc"){
    qualified_scen_name <- 'Walking'
  }else if(cs == "bi_sc"){
    qualified_scen_name <- 'Bicycling'
  }else if(cs == "car_sc"){
    qualified_scen_name <- 'Driving'
  }else if(cs == "mc_sc"){
    qualified_scen_name <- 'Motorcycling'
  }
  
  # readr::write_csv(whw_lng, paste0('results/multi_city/whw_matrices/whw_lng_', cs, '.csv'))
  
  whw_lng$scenario <- qualified_scen_name
  
  if (length(whw_list) == 0)
    whw_list <- whw_lng
  else
    whw_list <- rbind(whw_list, whw_lng)
  
  f <- ggplot(data = whw_lng) +
    aes(x = str_mode, fill = cas_mode, weight = value) +
    geom_bar(position = "stack") +
    scale_fill_brewer(palette = "Dark2") +
    labs(x = "Strike Mode", y = "# of incidents", title = paste("WHW - ", qualified_scen_name, scen)) +
    coord_flip() +
    facet_wrap(vars(city), scales = "free_y")
  
  file_list[[cs]] <- f
  
  
  #ggsave(f, file = paste0("results/multi_city/whw_matrices/plots/whw_", cs,".png"), limitsize = F, dpi = 300, scale = 1.5)
  
  d <- paste0("results/multi_city/whw_matrices/interactive_plots/whw_", cs,".html")
  
  #htmlwidgets::saveWidget(plotly::ggplotly(f), file.path(normalizePath(dirname(d)), basename(d)))
  #ggsave(f, file=paste0("results/multi_city/whw_matrices/whw_", cs,".png"), width = 14, height = 10, units = "cm")
  
  qual_name <- paste(qualified_scen_name, scen)
  st[[cs]] <- format(td, scientific = F)
  #cat('####', qual_name, '\n')
  #print(kable(format(td, scientific = F), caption = paste('Who Hit Whom (WHW) for all case cities for ', qual_name)))
  #cat('\n')
  
}

readr::write_csv(whw_list, paste0('results/multi_city/whw_matrices/whw_lng.csv'))

```

### Who hit whom matrix for all case cities {#whw_all}


```{r whw_print, results = 'asis', fig.width=7, fig.height=4, echo=FALSE}

list_temp <- list()
index <- 1

scen_names <- unique(whw_list$scenario)
for (i in 1:length(scen_names)){
  sn <- scen_names[i]
  cat('###', sn, ' scenario', '\n')
  
  temp <- whw_list %>% filter(scenario == sn) %>% dplyr::select(cas_mode)
  
  cas_mode <- unique(temp$cas_mode)
  
  for (j in 1:length(cas_mode)){
    # print(cat(scen_names[i], ' - ', cas_mode[j], ' - '))
    cm <- cas_mode[j]
    temp1 <- whw_list %>% filter(scenario == sn & cas_mode == cm) %>% spread(value = value, key = str_mode)
    
    temp1 <- temp1 %>% mutate_if(is.numeric, .funs = funs(case_when( . < 1 ~ round(., 2) ,  . >= 1 ~  as.numeric(round(.))))) %>%  mutate_if(is.numeric, ~as.character(.))
    
    list_temp[[index]] <- temp1
    
    index <- index + 1
    cat('\n')
    cat('####', cm, '\n')
    #print(kable(format(temp1, scientific = F), caption = paste('Who Hit Whom (WHW) for ', scen_names[i], 'scenario and ', cas_mode[j], ' mode')))
    
    ft <- flextable(temp1)
    ft <- add_header_row(ft, values = c(' ', 'strike mode'), colwidths = c(3, ncol(temp1) - 3))
    ft <- merge_v(ft, j = 1:3, part = 'body')
    #fix_border_issues(ft)
    
    
    cat('\n')
    
    cat(knit_print(ft))
    
    cat('\n')
    
  }
  
  cat('\n')
  
}

```

### Who hit whom matrix for all case cities as CSV {#whw_all_csv}

[View from](https://github.com/ITHIM/ITHIM-R/blob/master/results/multi_city/whw_matrices/whw_lng.csv)


<!-- ### DT - Who hit whom matrix for all case cities {#whw_all} -->
<!-- Baseline -->

<!-- ```{r dt} -->

<!-- #for (cs in names(all_whw)){ -->
<!-- td <- NULL -->

<!-- cs <- 'Baseline' -->

<!-- var <- scen_lt %>% filter(scen_name == cs) %>% dplyr::select(val) %>% as.character() -->

<!-- fname <- paste("whw_", var, ".csv") -->

<!-- td <- st[[var]] -->

<!-- DT::datatable(td, -->
<!--               extensions = 'Buttons', -->
<!--               escape = FALSE, -->
<!--               rownames = FALSE, -->
<!--               options = list(dom = 'Bfrtip', -->
<!--                              buttons = -->
<!--                                list('colvis', list( -->
<!--                                  extend = 'collection', -->
<!--                                  buttons = list(list(extend='csv', -->
<!--                                                      filename = fname), -->
<!--                                                 list(extend='excel', -->
<!--                                                      filename = fname)), -->
<!--                                  text = 'Download' -->
<!--                                )), -->
<!--                              scrollX = TRUE, -->
<!--                              pageLength = nrow(td), -->
<!--                              order=list(list(2,'desc')), -->
<!--                              columnDefs = list(list(visible=FALSE, targets=c(1:(ncol(td) - 1)))))) -->

<!-- # } -->

<!-- ``` -->

