---
title: "Practicals 7th and 8th sessions"
subtitle: "Physical Activity simulation and summary statistics"
author: "Ali Abbas and Lambed Tatah"
engine: knitr
resources: 
  - "data"
format: 
  live-html:
    embed-resources: true
webr:
  packages: ['ggplot2', 'tidyverse', 'plotly']
  resources:
    - "data/io.rds"
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}

## Goal

-   7th session. Simulation of individual level baseline Physicl Activity (PA) from travel and non-travel
-   8th session. Derive a synthetic population with reference PA and derive summary statistics.

Before we get into exercises, let's explore how this works. We will start off with an example Q&A below:

### Setting up question and answers

Fill in the blank so that the result of the *sum* is 10.

```{webr}
#| exercise: ex_0
1 + 2 + 3 + ______
```

```{webr}
#| exercise: ex_0
#| check: true
if (.result == 10) {
  list(message = "Great work!", correct = TRUE)
} else {
  list(message = "That's incorrect. Try again ", correct = FALSE)
}
```

::: {.hint exercise="ex1"}
You should make the expression sum to 10.
:::

::: {.solution exercise="ex1"}
**Solution:**

``` r
1 + 2 + 3 + 4
```
:::

On the first day, you would have run the model and saved the outputs in the `io` object. We have read it in the background and can access it throughout these exercises.

```{webr}
#| setup: true
#| exercise:
#|   - ex_1
#|   - ex_2
#|   - ex_3
#|   - ex_4
#|   - ex_5
#|   - ex_6
#|   - ex_7
#|   - ex_8
#|   - ex_9
#|   - ex_10

io <- readRDS("data/io.rds")
trips <- io$bogota$trip_scen_sets
active_travel_duration <- io$bogota$trip_scen_sets |> 
  filter(participant_id > 0) |> 
  mutate(stage_mode = case_when(grepl("walk", stage_mode) ~ 
                                  "pedestrian", TRUE ~ stage_mode), 
         stage_duration = stage_duration / 60) |> 
  group_by(participant_id, scenario) |> 
  reframe(dur_cyc_hrs = sum(stage_duration[stage_mode == "cycle"]),
          dur_ped_hrs = sum(stage_duration[stage_mode == "pedestrian"]))


```

### A closer look at the `ithim` object

Investigate the structure of the `io` object. If you need help, please explore `hints`.

```{webr}
#| exercise: ex_1
______(io)
```

```{webr}
#| exercise: ex_1
#| check: true
if (identical(.result, names(io))) {
  list(correct = TRUE, message = "Nice work!")
} else {
  list(correct = FALSE, message = "That's incorrect, sorry.")
}
```

:::: {.hint exercise="ex_1"}
::: {.callout-note collapse="false"}
### Hint 1

Consider using the `names()` function

``` r
io$bogota |> names()
```
:::
::::

### Now look at Bogota specific list called `bogota`

Similar to the io object (which is a list), let's investigate the structure of the `bogota` list stored within the `io` object. Use the previously learnt knowledge to explore it.

```{webr}
#| exercise: ex_2
______(io$bogota)
```

### Show the first few rows of the base population object

```{webr}
#| exercise: ex_3
______(io$bogota$base_pop)
```

### Create a summary of background PA by age and sex groups

```{webr}
#| exercise: ex_4
io$bogota$base_pop |> 
  group_by(______, ______) |> 
  reframe(mean_background_LTPA = 
            mean(work_ltpa_marg_met))
```

### See if males and females have the same background PA

Using `sex` column, we are interested in calculating `mean` value of the column `work_ltpa_marg_met` below.

```{webr}
#| exercise: ex_5
io$bogota$base_pop |> 
  ungroup() |> 
  group_by(______) |> 
  reframe(mean_background_LTPA = 
            mean(work_ltpa_marg_met))
```

## Read in the total PA volume for each participant

Let's read in the data frame called `mmets` that stores total PA volume (background and travel related) from the `io` object. Once read in, let's look at the structure of it:

```{webr}
#| exercise: ex_6
mmets <- io$bogota$outcomes$mmets
head(mmets)
```

## Make sure that they match with the io object

Get the `base_pop` dataset from the `bogota` object

```{webr}
#| exercise: ex_7
base_pop_pa <- io$bogota$______
```

:::: {.hint exercise="ex_2"}
::: {.callout-note collapse="false"}
## Hint 1

Consider using the `names()` function for the `io$bogota` object.

``` r
io$bogota |> names()
```
:::
::::

:::: {.hint exercise="ex_2"}
::: {.callout-note collapse="false"}
## Hint 2

You should look for the `base_pop` object

``` r
io$bogota$base_pop
```
:::
::::

:::: {.solution exercise="ex_2"}
::: {.callout-tip collapse="false"}
## Fully worked solution:

Identify where the `trip_scen_sets` data frame is stored in the `bogota` list, and then assign it to a variable called `trips`:

``` r
io$bogota$base_pop           #<1>
base_pop_pa <- io$bogota$base_pop  #<2>
```

1.  Identify the name of the object and then,
2.  Assign it the `trips`
:::
::::

### Under the hood for scenario definition

Using this `io` object, look at the calculations of PA volume by:

1.  Remind ourselves what the scenarios were - the 5 percent increase in `car`, `cycling` and `bus` modes.

```{webr}
#| echo: false
#| edit: false
#| output: true
#| warning: false

io <- readRDS("data/io.rds")

trips <- io$bogota$trip_scen_sets

total_trips <- trips |> dplyr::filter(scenario == "baseline") |> 
    distinct(trip_id, scenario, .keep_all = T) |> nrow()

prop <- trips |> 
    dplyr::filter(participant_id !=0) |> 
    distinct(trip_id, scenario, .keep_all = T) |> 
    group_by(scenario, trip_mode) |> 
    reframe(freq = round(sum(dplyr::n())/total_trips*100, 1)) |> 
    mutate(pd = freq - freq[scenario == 'baseline']) |> 
    filter(pd != 0)

prop[prop$scenario == "baseline",]$scenario <- "Baseline"
prop[prop$scenario == "sc_bus",]$scenario <- "Bus"
prop[prop$scenario == "sc_car",]$scenario <- "Car"
prop[prop$scenario == "sc_cycle",]$scenario <- "Cycling"

scen_colours <- c("Baseline" = '#b15928',
                  "Cycling" = '#abdda4',
                  "Car" = '#d7191c',
                  "Bus" = '#2b83ba',
                  "Motorcycle" = '#fdae61')

plotly::ggplotly(ggplot(prop) +
     aes(x = trip_mode, fill = scenario, weight = pd) +
     geom_bar() +
    scale_x_discrete(guide = guide_axis(angle = 90)) + 
    geom_text(aes(x = trip_mode, y = round(pd, 1), label = round(pd, 1)), size = 4, 
                                 position = position_dodge()) + scale_fill_manual(values = scen_colours) +
     facet_wrap(vars(scenario)) + 
     labs(title = "Scenario definition (by mode)", y = "Percentage (%)", x = "Trip Mode") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)))
```

## Travel related PA volume

### Read the `trip` dataset from the `io` object

```{webr}
#| exercise: ex_8

trips <- io$bogota$______
```

### Look at the columns of trips dataset

```{webr}
#| exercise: ex_9
head(trips)
```

#### Calculate duration per person for active travel modes (cycling and walking)

Using trips dataset, do the following to calculate time spent (duration) per person doing cycling and walking by following these steps:

-   But before that, we need to identify which modes contain active travels. They are: `cycling`, `pedestrian` and `walk_to_pt` (walking component of to and from the bus stops).

-   Each person with their demographic information (age and sex) is stored in the `base_pop`

-   Use that dataset to identify the number of people and then

-   Sum duration by each active mode

```{webr}
#| exercise: ex_10

# Initialize MET values for cycling and walking 
CYCLING_MET <- 6.8
WALKING_MET <- 3.5

active_travel_duration <- 

mmets_pp <- io$bogota$trip_scen_sets |> 
  filter(participant_id > 0) |> 
  mutate(stage_mode = case_when(grepl("walk", stage_mode) ~ 
                                  "pedestrian", TRUE ~ stage_mode), 
         stage_duration = stage_duration / 60) |> 
  group_by(participant_id, scenario) |> 
  # identify which stage_mode is either cycling or pedestrian and 
  reframe(total_mmets = sum(stage_duration[stage_mode == "______"]) * (CYCLING_MET - 1) + 
            sum(stage_duration[stage_mode == "______"]) * (WALKING_MET - 1)) |>  
  mutate(across(where(is.numeric), ~replace_na(., 0))) |> 
  left_join(io$bogota$base_pop |> dplyr::select(participant_id, work_ltpa_marg_met)) |> 
  mutate(overall_mmets = total_mmets + work_ltpa_marg_met) |> 
  dplyr::select(participant_id, scenario, overall_mmets) |> 
  pivot_wider(names_from = scenario, values_from = overall_mmets) |> 
  arrange(participant_id)

```

3.  Background PA volume (based on distribution as well as PA survey, if time permits)

4.  Look at distribution across scenarios (including baseline) by:

    1.  Age groups and gender groups

    2.  Identify who is benefiting or losing under each scenario

    3.  Discuss why is that the case
