---
title: "Practicals 7th and 8th sessions"
subtitle: "Physical Activity simulation and summary statistics"
author: "Ali Abbas and Lambed Tatah"
engine: knitr
resources: 
  - "data"
format: 
  live-html:
    embed-resources: true
webr:
  packages: ['tidyverse']
  resources:
    - "data/io.rds"
theme:
  light: cosmo
  dark: darkly
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}

## Learning objectives:

-   7th session. Simulation of individual level baseline Physical Activity (PA) from travel and non-travel
-   8th session. Derive a synthetic population with reference PA and show summary statistics.

Before we get into exercises, let's explore how this works. We will start off with an example Q&A below:

### Setting up question and answers

Fill in the blank so that the result of the **sum** is *10*.

```{webr}
#| exercise: ex_0
1 + 2 + 3 + ______
```

```{webr}
#| exercise: ex_0
#| check: true
if (.result == 10) {
  list(message = "Great work!", correct = TRUE)
} else {
  list(message = "That's incorrect. Try again ", correct = FALSE)
}
```

::: {.hint exercise="ex1"}
You should make the expression sum to 10.
:::

::: {.solution exercise="ex1"}
**Solution:**

``` r
1 + 2 + 3 + 4
```
:::

On the first day, you would have run the model and saved the outputs in the `io` object. We have read it in the background and can access it throughout these exercises.

```{webr}
#| setup: true
#| exercise:
#|   - ex_1
#|   - ex_2
#|   - ex_3
#|   - ex_4
#|   - ex_5
#|   - ex_6
#|   - ex_7
#|   - ex_8
#|   - ex_9
#|   - ex_10
#|   - ex_11
#|   - ex_12
#|   - ex_13
#|   - ex_14

# Initialize MET values for cycling and walking 
CYCLING_MET <- 6.8
WALKING_MET <- 3.5

io <- readRDS("data/io.rds")
trips <- io$bogota$trip_scen_sets
active_travel_duration <- io$bogota$trip_scen_sets |> 
  filter(participant_id > 0) |> 
  mutate(stage_mode = case_when(grepl("walk_to_pt", stage_mode) ~ 
                                  "pedestrian", TRUE ~ stage_mode), 
         stage_duration = stage_duration / 60) |> 
  group_by(participant_id, scenario) |> 
  reframe(dur_cyc_hrs = sum(stage_duration[stage_mode == "cycle"]),
          dur_ped_hrs = sum(stage_duration[stage_mode == "pedestrian"]))

travel_mmets <- active_travel_duration |> 
  group_by(participant_id, scenario) |> 
  reframe(total_travel_mmets = dur_cyc_hrs * (CYCLING_MET - 1) + 
            dur_ped_hrs * (WALKING_MET - 1)) 

mmets_pp <- travel_mmets |> 
  left_join(io$bogota$base_pop |> 
              dplyr::select(participant_id, 
                            work_ltpa_marg_met))

mmets_pp_total <- mmets_pp |> 
  mutate(total_mmets = total_travel_mmets + work_ltpa_marg_met)

mmets_pp_total_wide <- mmets_pp_total |> 
  dplyr::select(-c(total_travel_mmets, work_ltpa_marg_met)) |> 
  pivot_wider(names_from = scenario, values_from = total_mmets)

```

### A closer look at the `ithim` object

Investigate the structure of the `io` object. If you need help, please explore `hints`.

```{webr}
#| exercise: ex_1
______(io)
```

```{webr}
#| exercise: ex_1
#| check: true
if (identical(.result, names(io))) {
  list(correct = TRUE, message = "Nice work!")
} else {
  list(correct = FALSE, message = "That's incorrect, sorry.")
}
```

:::: {.hint exercise="ex_1"}
::: {.callout-note collapse="false"}
### Hint 1

Consider using the `names()` function

``` r
io$bogota |> names()
```
:::
::::

### Now look at Bogota specific list called `bogota`

Similar to the io object (which is a list), let's investigate the structure of the `bogota` list stored within the `io` object. Use the previously learnt knowledge to explore it.

```{webr}
#| exercise: ex_2
______(io$bogota)
```

### Show the first few rows of the base population object

```{webr}
#| exercise: ex_3
______(io$bogota$base_pop)
```

### Create a summary of background PA by age and sex groups

```{webr}
#| exercise: ex_4
io$bogota$base_pop |> 
  group_by(______, ______) |> 
  reframe(mean_background_LTPA = 
            mean(work_ltpa_marg_met))
```

### See if males and females have the same background PA

Using `sex` column, we are interested in calculating `mean` value of the column `work_ltpa_marg_met` below.

```{webr}
#| exercise: ex_5
io$bogota$base_pop |> 
  ungroup() |> 
  group_by(______) |> 
  reframe(mean_background_LTPA = 
            mean(work_ltpa_marg_met))
```

## Read in the total PA volume for each participant

Let's read in the data frame called `mmets` that stores total PA volume (background and travel related) from the `io` object. Once read in, let's look at the structure of it:

```{webr}
#| exercise: ex_6
mmets <- io$bogota$outcomes$mmets
______(mmets)
```

## Make sure that they match with the io object

Get the `base_pop` dataset from the `bogota` object

```{webr}
#| exercise: ex_7
base_pop_pa <- io$bogota$______
```

:::: {.hint exercise="ex_7"}
::: {.callout-note collapse="false"}
## Hint 1

Consider using the `names()` function for the `io$bogota` object.

``` r
io$bogota |> names()
```
:::
::::

:::: {.solution exercise="ex_7"}
::: {.callout-note collapse="false"}
## Hint 2

You should look for the `base_pop` object

``` r
io$bogota$base_pop
```
:::
::::

:::: {.solution exercise="ex_7"}
::: {.callout-tip collapse="false"}
## Fully worked solution:

Identify where the `trip_scen_sets` data frame is stored in the `bogota` list, and then assign it to a variable called `trips`:

``` r
io$bogota$base_pop           #<1>
base_pop_pa <- io$bogota$base_pop  #<2>
```

1.  Identify the name of the object and then,
2.  Assign it the `trips`
:::
::::

## Travel related PA volume

### Read the `trip` dataset from the `io` object

```{webr}
#| exercise: ex_8

trips <- io$bogota$______
```

### Look at the columns of trips dataset

```{webr}
#| exercise: ex_9
______(trips)
```

### Calculate duration per person for active travel modes (cycling and walking)

Using trips dataset, do the following to calculate time spent (duration) per person doing cycling and walking by following these steps:

-   But before that, we need to identify which modes contain active travels. They are: `cycling`, `pedestrian` and `walk_to_pt` (walking component of to and from the bus stops).

-   Rename short walks (`walk_to_pt`) to `pedestrian` mode

-   Sum duration by each active mode for each person.

```{webr}
#| exercise: ex_10
active_travel_duration <- io$bogota$trip_scen_sets |> 
  # Remove ghost trips - (bus and car vehicles)
  filter(participant_id > 0) |> 
  mutate(
      # Rename walk_to_pt to pedestrian
      stage_mode = case_when(grepl("walk_to_pt", stage_mode) ~ 
                                  "pedestrian", TRUE ~ stage_mode), 
      # Chage stage_duration in minutes to hours            
      stage_duration = stage_duration / 60) |> 
  # Group by participant_id for each scenario
  group_by(participant_id, scenario) |> 
  # Calculate overall duration per person per week spent in active travel
  reframe(dur_cyc_hrs = sum(stage_duration[stage_mode == "______"]),
          dur_ped_hrs = sum(stage_duration[stage_mode == "______"]))
# Show top rows
head(active_travel_duration)
```

### Calculate mMET hours per week from time spent in active travel

In order to calculate the total travel related PA for each person, we need to use the following function: weekly in hours \* mMET hours per week. For cycling, mMET hours per week is `5.8` and for walking, it is `2.5`. In order to have a combined travel related mMET hours per week, we sum together PA volume for `cycling` and `walking` together.

```{webr}
#| exercise: ex_11
travel_mmets <- 
  # Use active travel duration per person dataset
  active_travel_duration |> 
  # Group by participant_id and scenario
  group_by(participant_id, scenario) |> 
  reframe(total_travel_mmets = ______ * (CYCLING_MET - 1) + 
            ______ * (WALKING_MET - 1)) 

head(travel_mmets)
```

### Bring travel and non travel related PA together

Now that we have calculated travel related PA (in mMET hours per week) for each individual in the previous exercise. In this one, we'd like to bring in both the travel and the background PA together. Just to remind you that the background PA (again in the same unit as mMET hours per week) is stored in in the `io$bogota$base_pop` object.

```{webr}
#| exercise: ex_12
mmets_pp <- travel_mmets |> 
  left_join(io$bogota$base_pop |> dplyr::select(participant_id, work_ltpa_marg_met))

head(mmets_pp)
```

### Add travel and non-travel PA together

Sum background PA (which doesn't change throughout) and the travel PA (which does change in scenarios from baseline) to calculate overall PA volume for each person in a week.

```{webr}
#| exercise: ex_13
mmets_pp_total <- mmets_pp |> 
  mutate(total_mmets = ______ + ______)

head(mmets_pp_total)
```

### Change the layout `mmets_pp_total` to wide

Change the layout of the PA volume per person per scenario

```{webr}
#| exercise: ex_14
mmets_pp_total_wide <- mmets_pp_total |> 
  dplyr::select(-c(total_travel_mmets, work_ltpa_marg_met)) |> 
  pivot_wider(names_from = scenario, values_from = ______)

head(mmets_pp_total_wide)

```
